version: '3.6'
services:
    mysql:
        image: "mysql:8.0.29"
        container_name: mysql_server
        command: ['--default-authentication-plugin=mysql_native_password']
        environment:
            - MYSQL_DATABASE=default_db
            - MYSQL_ROOT_PASSWORD=my-pass
            - MYSQL_USER=user-name
            - MYSQL_PASSWORD=my-user-pass
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            network:
        #restart: always
    # # this code from: https://hub.docker.com/r/linuxserver/mysql-workbench 
    # mysql-workbench:
    #     image: lscr.io/linuxserver/mysql-workbench
    #     container_name: mysql-workbench
    #     environment:
    #     - PUID=1000
    #     - PGID=1000
    #     - TZ=Europe/London
    #     volumes:
    #     - /path/to/config:/config
    #     ports:
    #     - 3000:3000
    #     cap_add:
    #     - IPC_LOCK
    #     restart: unless-stopped
volumes:
    mysqldata: 
        name: mysql-server-volume
    # mysql-workbench: 

networks:
    # create Network By Default with directory name
    network:
        name: "easyapiservices-net"
    